# Generated by Django 5.1 on 2024-09-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('roles', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=100)),
            ],
        ),
    ]
